### PR TITLE
Manually scale the icon if it was passed as a pixbuf

### PR DESCRIPTION
**Pull request by azzar1**
Manually scale the icon if it was passed as a pixbuf.

### CODE REVIEW

**Comment by jhasse** [comment]
This is for HiDPI, right? Do you know an app where this is a problem so I can reproduce it?

**Comment by azzar1** [comment]
Telegram?

**Comment by azzar1** [comment]
And yes it's for HiDPI :D

**Comment by jhasse** [comment]
Can you post a before/after screenshot of the problem this PR is trying to solve?

I don't have a HiDPI screen and tried to emulate it by setting the window scale factor to 2, but GNOME Shell didn't scale correctly.

**Comment by azzar1** [comment]
Before the fix:
not_ok

After the fix:
ok

**Comment by jhasse** [comment]
Thanks :)

Your changes look good. Can you test though, if also adding the scale factor here

```
let qualifiedIconPixmapArray = sortedIconPixmapArray.filter(function(pixmap) {
                // we disqualify any pixmap that is bigger than our requested size
                return pixmap[0] <= iconSize * scale_factor && pixmap[1] <= iconSize * scale_factor
})
```

improves the image quality? We wouldn't want to disqualify HiDPI pixbufs.

**Comment by azzar1** [comment]
iconSize is already scaled there. I think there is no need to scale it
again.

On 3 Oct 2017 15:30, "Jan Niklas Hasse" <notifications@github.com> wrote:

Thanks :)

Your changes look good. Can you test though, if also adding the scale
factor here

let qualifiedIconPixmapArray = sortedIconPixmapArray.filter(function(pixmap) {
                // we disqualify any pixmap that is bigger than our
requested size
                return pixmap[0] <= iconSize * scale_factor &&
pixmap[1] <= iconSize * scale_factor
})

improves the image quality? We wouldn't want to disqualify HiDPI pixbufs.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ubuntu/gnome-shell-extension-appindicator/pull/95#issuecomment-333952623>,
or mute the thread

**Comment by jhasse** [comment]
Ups, yeah you're right. Thank you very much for the PR :)

**Pull request merged**
