### PR TITLE
feature: Add topicons-plus extension logic to AppIndicator extension

### PR DESCRIPTION
**Pull request by JingiJeong**
To handle legacy tray, merge topicons-plus extension logic with appindicator extension. Create topicons.js file and connect with original appindicator code.

### CODE REVIEW

**Comment by JingiJeong** [comment]
The task of porting the existing topicons-plus extension logic to the appindicator was performed. The following capture is a before and after comparison that works properly after the icon is transplanted, which is not normally created on the panel through the appindicator.
킹갓제너럴엠퍼럴갓뀨민연구원님

**Comment by 3v1n0** [comment]
Mhmh, so the idea isn't bad...

HOWEVER, in some places (like in ubuntu) we'd like not to enable this for all the apps, we actually may allow only JAVA and wine apps to use this.

So having settings to filter apps would be nice, and an option to disable this at all maybe

**Comment by JingiJeong** [comment]
Thank you for quick review. I know what a wine application is, but I am confused about what a JAVA app is. What exactly does an Ubuntu Java app mean?

**Comment by guihkx** [comment]
Thanks for implementing this! I've tested this with two programs, and here are my findings:

- [TurnFlash v2.10](https://www.nirsoft.net/utils/tflash2.html): Windows program running on Wine 6.6.
- [JDownloader](https://flathub.org/apps/details/org.jdownloader.JDownloader): Java program running using Flatpak.

TurnFlash displays the tray icon properly (blue "F" icon):

image

However, the icon is supposed to change when you left click on it, but that does not happen with this patch. It's also supposed to open a context menu when you right click, but that doesn't happen either.

It does work, however, while using [TopIcons Plus](https://extensions.gnome.org/extension/1031/topicons/):

https://user-images.githubusercontent.com/626206/115813275-41a4b780-a3c9-11eb-95fe-f1909b711994.mp4

JDownloader's tray icon is displayed as a black square (also happens with TopIcons Plus, by the way):

image

Double clicking the tray icon does bring the JDownloader window forward (as intended). Right clicking also opens the context menu successfully:

image

However, attempting to click on any of the options won't do anything and will close the context menu. Also happens with TopIcons Plus. :(

Using this patch (or TopIcons Plus), will create an additional window called JavaEmbeddedFrame, which is displayed when you Alt Tab:

https://user-images.githubusercontent.com/626206/115813804-3c943800-a3ca-11eb-8833-3cc52c756904.mp4

Also, this JavaEmbeddedFrame window can stay floating on the top-left side of other windows if you Alt Tab to it by mistake:

image

I tried to hide this JavaEmbeddedFrame window by setting `StartupWMClass` to JDownloader's `.desktop` file (as suggested [here](https://github.com/linuxmint/cinnamon/issues/728#issuecomment-538681978)), but it didn't do anything.

- **OS:** Arch Linux
- **GNOME:** 40

Cheers.

**Pull request closed without merging**
